---
- name: Containerd - Create worker directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    '{{ containerd_directories }}'

- name: Containerd - Download cni-plugin
  get_url:
    url: '{{ cni_plugin_url + "cni-plugins-linux-amd64-" + cni_plugin_version + ".tgz" }}'
    dest: /tmp/cni/cni-plugin.tar.gz
    mode: '0755'

- name: Containerd - Extracting cni plugin files
  unarchive:
    src: /tmp/cni/cni-plugin.tar.gz
    dest: /opt/cni/bin/
    remote_src: true

- name: Containerd - Cleaning downloaded files
  file:
    path: '/tmp/cni/'
    state: absent

- name: Containerd - Download containerd tarball's
  get_url:
    url: '{{ item }}'
    dest: /tmp/containerd/
    mode: '0755'
  loop: 
    - '{{ containerd_cri_url + "crictl-" + containerd_cri_version + "-linux-amd64.tar.gz" }}'
    - '{{ containerd_url + "containerd-" + containerd_version + "-linux-amd64.tar.gz" }}'

- name: Containerd - Extracting containerd files
  unarchive:
    src: '{{ item.src }}'
    dest: '{{ item.dst }}'
    remote_src: true
    extra_opts:
      '{{ item.extra.split(",") | default("") }}'
  loop:
    - { src: '{{ "/tmp/containerd/crictl-" + containerd_cri_version + "-linux-amd64.tar.gz" }}', dst: "/usr/local/bin/", extra: "" }
    - { src: '{{ "/tmp/containerd/containerd-" + containerd_version + "-linux-amd64.tar.gz" }}', dst: "/bin", extra: "--strip,1,bin/" }

- name: Containerd - Download runc bin
  get_url:
    url: '{{ item.src }}'
    dest: '{{ item.dst }}'
    mode: '0755'
  loop: 
    - { src: '{{ containerd_runc_url + containerd_runc_version + "/runc.amd64" }}', dst: "/usr/local/bin/runc" }

- name: Containerd - Cleaning containerd downloaded files
  file:
    path: '/tmp/containerd'
    state: absent

- name: Containerd - Adding containerd configuration and Service files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dst + item.src.split(".")[0] + "." + item.src.split(".")[1] }}'
    owner: root
    mode: '0640' 
  loop:
    '{{ containerd_templates }}'

- name: Containerd - Systemd reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Containerd - Enable containerd.service
  ansible.builtin.systemd:
    name: containerd
    enabled: yes
