---
- name: Installing containerd dependencie packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - "conntrack"
    - "ipset"
    - "socat"
  
- name: Adding kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter
    - nf_conntrack

- name: Create folders
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    "{{ folders }}"

- name: Download containerd and dependecies binaries
  get_url:
    url: "{{ item.url }}"
    checksum: "{{ item.checksum }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    # Generated on the default
    "{{ download }}"

- name: Extracting containerd and dependecies
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: true
    extra_opts:
      "{{ item.extra.split(',') | default('') }}"
  loop:
    # Generated on the default
    "{{ untar_files }}"

- name: Copy containerd config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0640"
  loop:
    - { src: "containerd.conf", dest: "/etc/modules-load.d/" }
    - { src: "99-kubernetes-cri.conf", dest: "/etc/sysctl.d/" }
    - { src: "config.toml", dest: "/etc/containerd/" }
    - { src: "containerd.service", dest: "/etc/systemd/system/" }

- name: Adding containerd configuration and Service files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest + item.src.split('.')[-3] + '.' + item.src.split('.')[-2] }}"
    owner: root
    mode: "0640" 
  loop:
    - { src: "10-bridge.conf.j2", dest: "/etc/cni/net.d/" }
    - { src: "99-loopback.conf.j2", dest: "/etc/cni/net.d/" }

- name: Systemd reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable containerd.service
  ansible.builtin.systemd:
    name: containerd
    enabled: yes
    state: started
