---
- name: Converge
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - name: "containerd"
      cntlr_cidr: "10.1.0.0/24"
      cri_version: "v1.21.0"
      containerd_version: "1.4.4"
      runc_version: "v1.0.0-rc93"
      cni_version: "0.4.0"
      cni_plugin_version: "v0.9.1"
