---
- name: Converge
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - name: "containerd"
      cntlr_cidr: "10.1.0.0/24"
      cri_url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/"
      cri_version: "v1.21.0"
      containerd_url: "https://github.com/containerd/containerd/releases/download/v"
      containerd_version: "1.3.6"
      runc_url: "https://github.com/opencontainers/runc/releases/download/"
      runc_version: "v1.0.0-rc91"
      cni_plugin_url: "https://github.com/containernetworking/plugins/releases/download/"
      cni_plugin_version: "v0.8.6"
      cni_version: "0.3.1"
